config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: { sessions: "sessions" }
  devise_for :partners, controllers: { sessions: "sessions", registrations: "registrations" }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

	authenticated :partner do
	  root to: "establishments#index", as: "partner_root"
	end

  root to: "landing#index"

  resources :dashboard
  resources :establishments

  resources :landing do
    collection do
      get :filter
    end
  end


  namespace :api do
    namespace :v1 do
      resources :directories do
        collection do
          get :cities
          get :categories
          get :establishments
        end
      end
    end
  end


end

app/models/admin.rb
class Admin < User
  devise :database_authenticatable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true

  has_many :establishments, dependent: :destroy

  scope :by_name, proc { |name|  where(name: name) unless name.blank? }

end

app/models/city.rb
class City < ActiveRecord::Base

  validates :name, presence: true

  has_many :establishments, dependent: :destroy

  scope :by_name, proc { |name|  where(name: name) unless name.blank? }


end

app/models/establishment.rb
# require 'geokit'

class Establishment < ActiveRecord::Base

  # acts_as_mappable
  # geocoded_by :address, units: :km

  validates :city, :address, presence: true

  # after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  belongs_to :city
  belongs_to :category

  # Scopes
  scope :by_city, proc { |city_id| where(city_id: city_id) unless city_id.blank? }
  scope :by_category, proc { |category_id| where(category_id: category_id) unless category_id.blank? }

  default_scope { where(is_verified: true) }



  def self.search(queries)
    finder = by_city(queries[:city_id])
    finder = finder.by_category(queries[:category_id])
    finder.order(:name)
  end

  def self.coordinates
    order(:name).map { |establishment| [establishment.name.gsub("'", "\\\\'"),
                                        establishment.latitude.to_f,
                                        establishment.longitude.to_f,
                                        establishment.address,
                                        establishment.contact_details,
                                        establishment.id,
                                        establishment.pin_img] }
  end

  def location
    [address, city.name].join(" ")
  end

  def image_url
    filepicker_url || "http://placehold.it/800x500"
  end

  def contact_details
    [mobile, landline].join(" ")
  end

  def pin_img
    case category.name
    when "Hospital" then "http://maps.google.com/mapfiles/kml/pal2/icon38.png"
    when "Banks" then "http://maps.google.com/mapfiles/kml/pal2/icon50.png"
    when "Police" then "http://maps.google.com/mapfiles/kml/pal2/icon24.png"
    when "Restaurants" then "http://maps.google.com/mapfiles/kml/pal2/icon32.png"
    when "Hotel" then "http://maps.google.com/mapfiles/kml/pal2/icon28.png"
    when "Gasoline" then "http://maps.google.com/mapfiles/kml/pal2/icon29.png"
    when "Services" then "http://maps.google.com/mapfiles/kml/pal2/icon6.png"
    when "Government" then "http://maps.google.com/mapfiles/kml/pal2/icon0.png"
    end
  end


end

app/models/partner.rb
class Partner < User

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :establishments

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :by_admins, -> { where(type: "Admin") }
  scope :by_partners, -> { where(type: "Partner") }

  def full_name
    [first_name, last_name].join(" ")
  end

end

app/controllers/api/v1/directories_controller.rb
class Api::V1::DirectoriesController < ApiController

  def cities
    cities = City.by_name(params[:name])
    render json: cities, status: 200
  end

  def categories
    categories = Category.by_name(params[:name])
    render json: categories, status: 200
  end

  def establishments
    establishments = Establishment.search(params)
    render json: establishments, status: 200
  end


end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :check_user_status

private

  def check_user_status
    if current_partner
      if current_partner.status == 'pending'
        sign_out current_partner
      end
    end
  end


end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController

  before_action :authenticate_partner!
  before_action :set_options, only: [:edit, :new]
  before_action :find_establishment, only: [:edit, :update]

  def index
    @establishments = current_partner.establishments
  end

  def new
    @establishment = current_partner.establishments.new
  end

  def create
    @establishment = current_partner.establishments.create(establishment_params)
    redirect_to establishments_path
  end

  def edit
  end

  def update
    @establishment.update(establishment_params)
    redirect_to establishments_path
  end

  def destroy
  end

private

  def find_establishment
    @establishment = Establishment.find(params[:id])
  end

  def set_options
    @options = OptionsPresenter.new
  end

  def establishment_params
    params.require(:establishment).permit(:name, :address, :city_id, :category_id, :landline, :mobile, :open_hours, :filepicker_url)
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  before_action :set_options

  def index
    render layout: "start"
  end

  def filter
    @establishments = Establishment.search(params)
    @places = @establishments.coordinates
  end


 private

 def set_options
   @options = OptionsPresenter.new
 end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  layout "authentication"

  protected
  def after_sign_up_path_for(resource)
    case resource.type
    when "Admin" then  rails_admin_path
    when "Partner" then  partner_root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  layout "authentication"

  protected
  def after_sign_in_path_for(resource)
    case resource.type
    when "Admin" then  rails_admin_path
    when "Partner" then partner_root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/establishments/_form.haml
.form-container.form-horizontal
  .form-group
    #map-canvas{ style: "height: 500px;" }
    %input#input-autocomplete{ size: 100 }

  .form-group
    %label.col-sm-3.control-label Name
    .col-sm-9
      = f.text_field :name, class: "form-control", required: true

  .form-group
    %label.col-sm-3.control-label Address
    .col-sm-9
      = f.text_area :address, class: 'form-control'

  .form-group
    %label.col-sm-3.control-label City
    .col-sm-9
      = f.select :city_id, @options.cities, { prompt: "Select a City" }, class: 'form-control'

  .form-group
    %label.col-sm-3.control-label Category
    .col-sm-9
      = f.select :category_id, @options.categories, { prompt: "Select a Category" }, class: 'form-control'

  .form-group
    %label.col-sm-3.control-label Landline
    .col-sm-9
      = f.text_field :landline, class: 'form-control form-input'

  .form-group
    %label.col-sm-3.control-label Mobile
    .col-sm-9
      = f.text_field :mobile, class: 'form-control form-input'

  .form-group
    %label.col-sm-3.control-label Open Hours
    .col-sm-9
      = f.text_area :open_hours, class: 'form-control form-input'

  .form-group
    %label.col-sm-3.control-label Image
    .col-sm-6
      .crop
        = image_tag @establishment.image_url, class: "image-preview img-responsive img-establishment"

        = hidden_field_tag :latitude, value: @establishment.latitude
        = hidden_field_tag :longitude, value: @establishment.longitude

  .form-group
    %label.col-sm-3.control-label
    .col-sm-9
      = f.filepicker_field :filepicker_url, data: { "fp-apikey" => "AY9xVsY6mSJuaAaG0S7Zjz" }, onchange: 'file_preview(event.fpfile.url)'


:javascript
  $(function() {
    window.file_preview = function(url) {
      $('.image-preview').attr('src', url)
    }

    var mapOptions;

    if(#{@establishment.latitude.present? && @establishment.longitude.present?}) {
      mapOptions = {
          center: { lat: parseFloat("#{@establishment.latitude}"), lng: parseFloat("#{@establishment.longitude}") },
          zoom: 18,
          mapTypeId: google.maps.MapTypeId.ROADMAP
      };
    }
    else {
      mapOptions = {
          center: { lat: 12.764251, lng: 122.362238 },
          zoom: 6,
          mapTypeId: google.maps.MapTypeId.ROADMAP
      };
    }

    map = new google.maps.Map(document.getElementById('map-canvas'),mapOptions);

    input = document.getElementById('input-autocomplete');

    console.log(mapOptions.center.lat);
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(mapOptions.center.lat, mapOptions.center.lng),
      map: map
    });

    addInputAutocomplete();
  });

  function addInputAutocomplete(){
    map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

    var options = {
        types: ['establishment']
    };

    autocomplete = new google.maps.places.Autocomplete(input, options);
    google.maps.event.addListener(autocomplete, 'place_changed', function(){
        fillInAddress();
        var place = autocomplete.getPlace();
    });

  }

  function fillInAddress() {
    var place = autocomplete.getPlace();

    map = new google.maps.Map(document.getElementById('map-canvas'),{
        center: place.geometry.location,
        zoom: 15,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    addInputAutocomplete();

    var address_components = place.address_components;

    document.getElementById('latitude').value = place.geometry.location.lat();
    document.getElementById('longitude').value = place.geometry.location.lng();
    document.getElementById('establishment_name').value = place.name;
    document.getElementById('establishment_address').value = place.formatted_address;
    document.getElementById('establishment_landline').value = place.international_phone_number;

  }

    

app/views/establishments/_results.haml
- @establishments.each do |establishment|
  .col-md-3.col-sm-6.hero-feature
    .thumbnail
      .crop
        = image_tag establishment.image_url, class: "img-responsive img-establishment"
      .caption
        %ul.details
          %li=image_tag establishment.pin_img, data: { toggle: "tooltip"}, title: establishment.category.name
          %li=image_tag "landing/verified.png", data: { toggle:  "tooltip" }, title: "Verified" if establishment.is_verified
        %h4= truncate(establishment.name, length:20)
        %p.minimize= establishment.location
        %p= establishment.open_hours
        %p= establishment.contact_details
        %p
          %a.btn.btn-primary{href: edit_establishment_path(establishment)} Edit
          %a.btn.btn-default{href: establishment_path(establishment), method: 'delete'} Delete


:javascript
  $(function() {
    $('[data-toggle="tooltip"]').tooltip()
    Connectory.minimize.initialize()
  })

app/views/establishments/edit.haml
.container-fluid.col-centered.col-xs-10
  .row
    .panel.panel-default.clearfix
      .panel-heading
        %h2.panel-title Edit Establishment
      .col-xs-12
        = form_for @establishment, method: :put do |f|
          = render 'form', f: f
          .panel-footer.col-md-12
            .pull-right= f.submit 'Save', class: 'btn btn-primary form-btn'

app/views/establishments/index.haml
- if @establishments.any?
  .row.text-center
    = render 'results'
- else
  .jumbotron
    %h1.text-center You have no establishments yet.
    .text-center= link_to "Create one now", new_establishment_path, class: 'btn btn-primary btn-lg'

app/views/establishments/new.haml
.container-fluid.col-centered.col-xs-10
  .row
    .panel.panel-default.clearfix
      .panel-heading
        %h2.panel-title Add New Establishment
      .col-xs-12
        = form_for @establishment do |f|
          = render 'form', f: f
          .panel-footer.col-md-12
            .pull-right= f.submit 'Save', class: 'btn btn-primary form-btn'

app/views/establishments/show.haml
%h1= @establishment.name

app/views/landing/_filter.haml
.panel-default.panel-fixed
  .panel-body
    = form_tag filter_landing_index_path, method: :get do
      .form-group.col-md-4
        = select_tag :city_id, options_for_select(@options.cities, params[:city_id]), class: "form-control", prompt: "All Cities"
      .form-group.col-md-4
        = select_tag :category_id, options_for_select(@options.categories, params[:category_id]), class: "form-control", prompt: "All Categories"
      .form-group.col-md-4
        = submit_tag "Search", class: "btn btn-primary form-control"

app/views/landing/_results.haml
- @establishments.each do |establishment|
  .col-md-6.hero-feature
    .thumbnail
      .crop
        = image_tag establishment.image_url, class: "img-responsive img-establishment"
      .caption
        %h4= link_to truncate(establishment.name, length:20), "#", class: "locate-pin", data: { lat: establishment.latitude, lng: establishment.longitude }
        %p.minimize= establishment.location
        %p= establishment.open_hours
        %ul.details
          %li=image_tag establishment.pin_img, data: { toggle: "tooltip"}, title: establishment.category.name
          %li=image_tag "landing/verified.png", data: { toggle:  "tooltip" }, title: "Verified" if establishment.is_verified


:javascript
  $(function() {
    Connectory.minimize.initialize()
    $('[data-toggle="tooltip"]').tooltip()
    $(".locate-pin").click(function() {
      set_map_center($(this).data("lat"), $(this).data("lng"))
    })

    function set_map_center(lt, lng){
      var pos = new google.maps.LatLng(lt, lng)
      for(var i=0;i<markers.length;i++){
          if(markers[i].position.equals(pos))
              google.maps.event.trigger(markers[i], 'click');

      }
    }

  })

app/views/landing/filter.haml
#map-canvas
#main.container-fluid
  .row
    .col-md-6.vcenter.filter
      = render 'filter'
    .col-md-6.col-lg-6.vcenter
      .sidebar
        %p.count Displaying #{@establishments.count} establishments
        = render 'results'


:javascript
  $(function() {
    Connectory.maps.initialize(#{@places})
  })

:css
  .count {
    padding: 10px 0 0 18px;
  }

  .filter {
    background-color: #565a5b;
    border-bottom: 1px solid #bbb;
  }

  .sidebar {
    overflow-y: auto;
    height: 580px;
  }

  .vcenter {
    padding: 0;
    display: inline-block;
    vertical-align: middle;
    float: none;
  }

app/views/landing/index.haml
.banner-wrapper
  .title-container
    .headline
      .combo
        = image_tag "landing/logo-big.png"
        %span.service-content
          %p.subtitle Everyone within reach
        = link_to "Search Now", filter_landing_index_path, class: "btn btn-semi-transparent btn-contrast btn-large"

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Connectory
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "http://api.filepicker.io/v2/filepicker.js"  
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places"
    = csrf_meta_tags
  %body
    = render "shared/navbar_auth"
    .container
      = render 'shared/messages', flash: flash
      = yield

app/views/layouts/authentication.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Connectory
    = stylesheet_link_tag    'authentication', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.auth-body
    = render 'shared/messages', flash: flash
    = yield

app/views/layouts/landing.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Connectory
    = stylesheet_link_tag    'landing', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'landing', 'data-turbolinks-track' => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places"
    = csrf_meta_tags
  %body
    = render 'shared/navbar_landing'
    = render 'shared/messages', flash: flash
    = yield

app/views/layouts/start.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Connectory
    = stylesheet_link_tag 'start', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.start
    = yield

app/views/shared/_messages.haml
- flash.each do |type, message|
  :javascript
    $(function() {
      humane.log('#{message}', { timeout: 5000, clickToClose: true, addnCls: 'humane-jackedup-#{type} humane-message' })
    });

app/views/shared/_navbar_auth.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/"}
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        - if action_name != 'index'
          %li
            = link_to "All Establishments", establishments_path
        %li
          = link_to "New Establishment", new_establishment_path

      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to current_partner.full_name, "/"
        %li
          = link_to "Log Out", destroy_partner_session_path, method: :delete

app/views/shared/_navbar_landing.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "/landing/filter"}
    #navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "Become a Partner", new_partner_registration_path
        %li
          = link_to "Sign In", new_partner_session_path